### ISSUE TITLE
No longer working on github.com

### ISSUE THREAD

**Issue by tekumara** [zachwhaley/squashed-merge-message#23]
Is it just me or does this no longer work on github.com?

I've "This can read and change site data" = "On github.com" but when I press the Squash and Merge button it takes the title and content from the commit message, not the PR description.

**Comment by zachwhaley** [comment]
I can also confirm it is not working.

Looking into it...

**Comment by zachwhaley** [comment]
It would seem that GitHub has started populating that element dynamically.

When I debug squashed-merge-message, I find that it can't find the PR merge panel element because it doesn't exist yet.

![Screen Shot 2021-05-17 at 10 53 33 AM](https://user-images.githubusercontent.com/2996465/118519202-84bf2580-b6fe-11eb-9515-5dd2c7953d3f.png)
